import json

roles = {
    "Sheep": "A sheep. It has wool, hooves, and eats grass. It goes 'Baa'.",
    "Pig": "A pig. It has a snout, hooves, and loves mud and carrots. It goes 'Oink'.",
    "Cow": "A cow. It produces milk, has hooves, and eats wheat. It goes 'Moo'.",
    "Chicken": "A chicken. It has feathers, lays eggs, and eats seeds. It goes 'Cluck'.",
    "Zombie": "An undead zombie. It is rotting, slow, burns in sunlight, and craves brains. It goes 'Uuuhhh'.",
    "Skeleton": "An undead skeleton. It is made of bones, shoots arrows with a bow, and burns in sunlight. It goes 'Rattle'.",
    "Creeper": "A creeper. It is green, explosive, has four tiny legs, and hates cats. It goes 'Sssss'.",
    "Spider": "A giant spider. It has 8 legs, multiple eyes, climbs walls, and weaves webs. It goes 'Hiss'.",
    "Enderman": "An enderman. It is tall, dark, teleports, hates water, and gets angry if stared at.",
    "Villager": "A villager. It has a large nose, trades items for emeralds, and lives in a village. It goes 'Hmm'.",
    "Cat": "A domestic cat. It has fur, a tail, chases mice, and scares away creepers. It goes 'Meow'.",
    "Wolf": "A wolf. It has fur, hunts sheep, and can be tamed with bones. It goes 'Woof'.",
    "Slime": "A slime. It is a bouncy, green gelatinous cube that splits when hit. It goes 'Squish'.",
    "Ghast": "A ghast. It is a massive floating ghost that shoots fireballs and cries. It goes 'Eeehhh'.",
    "Zombie Piglin": "An undead piglin. It carries a golden sword and attacks in swarms if provoked.",
    "Witch": "A witch. It wears a pointy hat, brews potions, and laughs menacingly. It goes 'Hehehe'.",
    "Bat": "A bat. It has wings, flies in dark caves, and hangs upside down. It goes 'Squeak'.",
    "Horse": "A horse. It has hooves, can be ridden, and eats hay and apples. It goes 'Neigh'.",
    "Donkey": "A donkey. It has long ears, carries chests, and eats wheat. It goes 'Hee-haw'.",
    "Mule": "A mule. It is the sterile offspring of a horse and donkey, and can carry chests.",
    "Ocelot": "A wild ocelot. It lives in jungles, has spotted fur, and is very shy.",
    "Squid": "A squid. It has tentacles, lives underwater, and squirts black ink. It goes 'Squibble'.",
    "Glow Squid": "A glow squid. It is luminescent, has tentacles, and lives in deep water.",
    "Axolotl": "An axolotl. It is an adorable amphibious creature that hunts fish and can play dead.",
    "Bee": "A bee. It has wings, a stinger, collects pollen, and makes honey. It goes 'Buzz'.",
    "Fox": "A fox. It has orange or white fur, a bushy tail, sleeps during the day, and hunts chickens.",
    "Panda": "A panda. It is black and white, eats bamboo, and loves to roll around.",
    "Polar Bear": "A polar bear. It has thick white fur, lives in ice biomes, and protects its cubs fiercely.",
    "Rabbit": "A rabbit. It has long ears, hops around quickly, and loves carrots.",
    "Turtle": "A sea turtle. It has a hard shell, swims in oceans, and lays eggs on the beach.",
    "Dolphin": "A dolphin. It is playful, swims in oceans, and gives a speed boost to swimmers.",
    "Cod": "A cod. It is a common fish that swims in schools in oceans.",
    "Salmon": "A salmon. It is a fish that swims in rivers and oceans.",
    "Pufferfish": "A pufferfish. It inflates and poisons anything that gets too close.",
    "Tropical Fish": "A tropical fish. It comes in vibrant colors and swims in warm oceans.",
    "Wandering Trader": "A wandering trader. It travels with llamas and trades exotic goods. It goes 'Hmm'.",
    "Trader Llama": "A trader llama. It carries colorful carpets and spits at zombies.",
    "Llama": "A llama. It has wool, carries chests, and spits when annoyed.",
    "Parrot": "A parrot. It has colorful feathers, flies, imitates mob sounds, and loves seeds.",
    "Mooshroom": "A mooshroom. It is a cow covered in red mushrooms and produces mushroom stew.",
    "Iron Golem": "An iron golem. It is made of iron blocks, protects villages, and gives poppies to children.",
    "Snow Golem": "A snow golem. It is made of snow, wears a pumpkin head, and throws snowballs.",
    "Silverfish": "A silverfish. It is a small, gray insect that hides in stone blocks and swarms enemies.",
    "Endermite": "An endermite. It is a small purple bug born from ender pearls and is hated by endermen.",
    "Cave Spider": "A cave spider. It is small, venomous, climbs walls, and lives in abandoned mineshafts.",
    "Blaze": "A blaze. It floats, is made of fire and rods, and shoots fireballs in the Nether.",
    "Magma Cube": "A magma cube. It is a bouncy, fiery slime from the Nether.",
    "Wither Skeleton": "A wither skeleton. It is a tall, black skeleton with a stone sword that inflicts the Wither effect.",
    "Piglin": "A piglin. It loves gold, wields a crossbow or sword, and lives in the Nether.",
    "Piglin Brute": "A piglin brute. It is heavily scarred, wields an axe, and fiercely guards bastions.",
    "Hoglin": "A hoglin. It is a giant, aggressive boar that lives in the Nether and drops porkchops.",
    "Zoglin": "A zoglin. It is an undead hoglin that is extremely aggressive to everything.",
    "Strider": "A strider. It has long legs, walks on lava, and loves warped fungi.",
    "Ghast": "A ghast. It is a giant, crying, floating ghost in the Nether that shoots explosive fireballs.",
    "Phantom": "A phantom. It is a flying undead creature that attacks players who haven't slept.",
    "Drowned": "A drowned. It is an underwater zombie that can swim and throw tridents.",
    "Husk": "A husk. It is a dry zombie from the desert that doesn't burn in sunlight.",
    "Stray": "A stray. It is a frosty skeleton from ice biomes that shoots slowness arrows.",
    "Pillager": "A pillager. It is an illager armed with a crossbow that raids villages.",
    "Vindicator": "A vindicator. It is an illager armed with an iron axe that charges at enemies.",
    "Evoker": "An evoker. It is an illager mage that summons fangs and vexes.",
    "Vex": "A vex. It is a tiny, flying, ghostly creature with a sword, summoned by evokers.",
    "Ravager": "A ravager. It is a massive, horned beast that destroys crops and charges enemies.",
    "Warden": "A warden. It is blind, massive, and hunts by sound and smell in the deep dark.",
    "Goat": "A goat. It lives in mountains, jumps high, and rams anything that gets too close.",
    "Allay": "An allay. It is a small, blue, flying fairy that collects items and loves music.",
    "Frog": "A frog. It hops around, eats small slimes, and croaks in swamps.",
    "Tadpole": "A tadpole. It is a baby frog that swims in water before growing legs.",
    "Camel": "A camel. It is tall, has a hump, can carry two riders, and dashes over ravines.",
    "Sniffer": "A sniffer. It is a large, ancient creature that sniffs the ground for seeds."
}

# The mod might use the entity's namespaced ID or just the translation key. 
# Looking at contextData.put("entity_type", entity.method_5864().method_5897().getString());
# entity.getType().getName().getString() gives the localized name like "Sheep", "Zombie", etc.
# We will use exactly those localized English names as keys.

with open("e:/Projects/MobChat/CreatureChat/data/creaturechat/custom_roles.json", "w", encoding="utf-8") as f:
    json.dump(roles, f, indent=4, ensure_ascii=False)
